MovieApp.Web/Models/MoviesViewModel.cs
using MovieApp.Web.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieApp.Web.Models
{
    public class MoviesViewModel
    {
        public List<Movie> Movies { get; set; }
    }
}

MovieApp.Web/Controllers/MoviesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MovieApp.Web.Data;
using MovieApp.Web.Entity;
using MovieApp.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieApp.Web.Controllers
{
    public class MoviesController : Controller
    {
        private readonly MovieContext _context;
        public MoviesController(MovieContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult List(int? id, string q)
        {
            var controller = RouteData.Values["controller"];
            var action = RouteData.Values["action"];
            var genreId = RouteData.Values["id"];

            var kelime = HttpContext.Request.Query["q"].ToString();

            //var movies = MovieRepository.Movies;
            var movies = _context.Movies.AsQueryable();
            if (id != null)
            {
                movies = movies
                    .Include(m => m.Genres)
                    .Where(m => m.Genres.Any(g=>g.GenreId==id));
            }

            if (!string.IsNullOrEmpty(q))
            {
                movies = movies.Where(i => i.Title.ToLower().Contains(q.ToLower()) || i.Description.ToLower().Contains(q.ToLower()));
            }

            var model = new MoviesViewModel()
            {
                Movies = movies.ToList()
            };
            return View("List", model);
        }

        public IActionResult Details(int id)
        {
            return View(_context.Movies.Find(id));
        }

        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Genres = new SelectList(_context.Genres.ToList(), "GenreId", "Name");
            return View();
        }

        [HttpPost]
        public IActionResult Create(Movie movie)
        {
            if (ModelState.IsValid)
            {
                _context.Movies.Add(movie);
                _context.SaveChanges();
                //  MovieRepository.Add(movie);
                TempData["Message"] = $"{movie.Title} isimli film eklendi.";

                return RedirectToAction("List");
            }
            ViewBag.Genres = new SelectList(_context.Genres.ToList(), "GenreId", "Name");
            return View();
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {

            ViewBag.Genres = new SelectList(_context.Genres.ToList(), "GenreId", "Name");
            return View(_context.Movies.Find(id));
        }

        [HttpPost]
        public IActionResult Edit(Movie movie)
        {
            if (ModelState.IsValid)
            {
                //MovieRepository.Edit(movie);
                //movies/details/1
                _context.Movies.Update(movie);
                _context.SaveChanges();
                TempData["Message"] = $"{movie.Title} isimli film güncellendi.";

                return RedirectToAction("Details", "Movies", new { @id = movie.MovieId });
            }
            ViewBag.Genres = new SelectList(_context.Genres.ToList(), "GenreId", "Name");
            return View(movie);
        }

        [HttpPost]
        public IActionResult Delete(int MovieId, string Title)
        {
            //MovieRepository.Delete(MovieId);
            var entity = _context.Movies.Find(MovieId);
            _context.Movies.Remove(entity);
            _context.SaveChanges();
            TempData["Message"] = $"{Title} isimli film silindi.";
            return RedirectToAction("List");
        }
    }
}

MovieApp.Web/ViewComponents/GenresViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MovieApp.Web.Data;
using MovieApp.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieApp.Web.ViewComponents
{
    public class GenresViewComponent : ViewComponent
    {
        private readonly MovieContext _context;
        public GenresViewComponent(MovieContext context)
        {
            _context = context;
        }
        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedGenre = RouteData.Values["id"];
            return View(_context.Genres.ToList());
        }
    }
}

MovieApp.Web/Views/Movies/Create.cshtml
@model Movie
<h1>Create Movie</h1>

<hr />

<form method="post" asp-controller="Movies" asp-action="Create">
    <div class="form-group">
        <label asp-for="Title"></label>
        <input asp-for="Title" class="form-control" />
        <span asp-validation-for="Title" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Description"></label>
        <textarea asp-for="Description" class="form-control"></textarea>
        <span asp-validation-for="Description" class="text-danger"></span>

    </div>
    
    <div class="form-group">
        <label asp-for="ImageUrl"></label>
        <input asp-for="ImageUrl" class="form-control" />
        <span asp-validation-for="ImageUrl" class="text-danger"></span>

    </div>
    @*<div class="form-group">
        <label asp-for="GenreId"></label>
        <select asp-for="GenreId" asp-items="@ViewBag.Genres" class="form-control">
            <option selected disabled>Seçiniz</option>
        </select>
        <span asp-validation-for="GenreId" class="text-danger"></span>

    </div>*@
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

MovieApp.Web/Views/Movies/Details.cshtml
@model Movie

<div class="card">
    <div class="row">
        <div class="col-md-3">
            <img src="/img/@Model.ImageUrl" class="card-img" />
        </div>
        <div class="col-md-9">
            <div class="card-body">
                <h5 class="card-title">@Model.Title</h5>
                <p class="card-text">@Html.Raw(Model.Description)</p> <!--Html etiketleri yorumlanmış olarak gelicek.-->
              
            </div>
        </div>
    </div>
</div>

MovieApp.Web/Views/Movies/Edit.cshtml
@model Movie
<h1>Edit Movie</h1>

<hr />

<form method="post" asp-controller="Movies" asp-action="Edit">
    <input type="hidden" name="MovieId" value="@Model.MovieId" />
    <div class="form-group">
        <label asp-for="Title"></label>
        <input asp-for="Title" class="form-control" value="@Model.Title" />
        <span asp-validation-for="Title" class="text-danger"></span>

    </div>
    <div class="form-group">
        <label asp-for="Description"></label>
        <textarea asp-for="Description" class="form-control" value="@Model.Description"></textarea>
        <span asp-validation-for="Description" class="text-danger"></span>

    </div>
    
    <div class="form-group">
        <label asp-for="ImageUrl"></label>
        <input asp-for="ImageUrl" class="form-control" value="@Model.ImageUrl"/>
    </div>
    @*<div class="form-group">
        <label asp-for="GenreId"></label>
        <select asp-for="GenreId" asp-items="@ViewBag.Genres" class="form-control">
            <option selected disabled>Seçiniz</option>
        </select>
        <span asp-validation-for="GenreId" class="text-danger"></span>

    </div>*@
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

MovieApp.Web/Views/Movies/Index.cshtml
<p>Movies/Index</p> 

MovieApp.Web/Views/Movies/List.cshtml
@model MoviesViewModel


<h1>Film Listesi</h1>

<div id="filmler">
    @if (Model.Movies.Count() > 0)
    {
        @foreach (var movie in Model.Movies)
        {
            @await Html.PartialAsync("_movie", movie)
        }
    }
    else
    {
        <div class="alert alert-warning">
            Film bulunamadı.
        </div>
    }

</div>
@if (TempData["Message"] != null)
{
    @section message{
        @await Html.PartialAsync("_message", (string)TempData["Message"])

    }
}


@section menu{

    @await Component.InvokeAsync("Genres")

    @*@await Html.PartialAsync("_menu",Model.Genres)*@
}